'use strict';const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),W=require('../domain/syntheticWorkflow');const{readiness,requireProviders}=require('../services/providerBoundary');const hash=c=>c.repeat(64);
function input(overrides={}){return{name:'orders',version:'v1',purpose:'test fraud detection without personal data',classification:'confidential',generatorVersion:'local-deterministic-1',recordCount:100,seed:42,schema:[{name:'id',type:'uuid'},{name:'amount',type:'number',min:1,max:1000,scale:2},{name:'status',type:'enum',values:['paid','refunded']},{name:'customer_token',type:'string',pii:true,transform:'tokenize'}],privacy:{policyVersion:'privacy-1',epsilon:1,kAnonymity:5},sourceEvidence:[{digest:hash('a'),purpose:'distribution statistics',consentOrAuthority:true}],...overrides};}
test('spec validation requires versioned schema, scale, seed, privacy budget, and purpose-bound evidence',()=>{const result=W.validateSpec(input());assert.equal(result.ok,true);assert.match(result.spec.specDigest,/^[a-f0-9]{64}$/);const bad=W.validateSpec(input({recordCount:0,sourceEvidence:[]}));assert.equal(bad.ok,false);assert.match(bad.errors.join(' '),/recordCount/);assert.match(bad.errors.join(' '),/evidence/);});
test('PII fields require an allow-listed transform and privacy budget is bounded',()=>{const spec=input();spec.schema[3].transform='copy';spec.privacy.epsilon=20;const result=W.validateSpec(spec);assert.equal(result.ok,false);assert.match(result.errors.join(' '),/PII transform/);assert.match(result.errors.join(' '),/epsilon/);});
test('local fixture generation is deterministic and schema-constrained',()=>{const spec=W.validateSpec(input()).spec,a=W.generateBatch(spec,10),b=W.generateBatch(spec,10);assert.deepEqual(a,b);assert.equal(a.records.length,10);assert.ok(a.records.every(row=>row.amount>=1&&row.amount<=1000));assert.ok(a.records.every(row=>['paid','refunded'].includes(row.status)));assert.match(a.batchDigest,/^[a-f0-9]{64}$/);});
test('generation rejects unvalidated specs and oversized batches',()=>{const spec=W.validateSpec(input()).spec;assert.throws(()=>W.generateBatch({...spec,specDigest:'bad'},10),/validated spec/);assert.throws(()=>W.generateBatch(spec,101),/bounded count/);});
test('quality evaluation measures schema, uniqueness, relationships, distribution, privacy, utility, and latency',()=>{const spec=W.validateSpec(input()).spec,batch=W.generateBatch(spec,20),metrics={schemaValidityBps:10000,uniquenessBps:10000,referentialIntegrityBps:10000,distributionSimilarityBps:9400,privacyAttackResistanceBps:9800,utilityBps:9000,latencyMs:100,evaluatorVersion:'eval-1',evidenceDigest:hash('b')},passed=W.evaluate(spec,batch,metrics);assert.equal(passed.evaluation.passed,true);const failed=W.evaluate(spec,batch,{...metrics,privacyAttackResistanceBps:5000});assert.deepEqual(failed.evaluation.failed,['privacyAttackResistanceBps']);});
test('privacy review binds policy, risk evidence, and excludes retained personal data',()=>{const spec=W.validateSpec(input()).spec,review={policyVersion:'privacy-1',riskEvidenceDigest:hash('c'),reidentificationRiskBps:100,maxRiskBps:500,rawPersonalDataRetained:false};assert.equal(W.privacyReview(spec,review).ok,true);const bad=W.privacyReview(spec,{...review,reidentificationRiskBps:800,rawPersonalDataRetained:true});assert.equal(bad.ok,false);assert.match(bad.errors.join(' '),/exceeds/);assert.match(bad.errors.join(' '),/raw personal/);});
test('release requires passed evaluation, privacy evidence, providers, and independent approval',()=>{const spec=W.validateSpec(input()).spec,batch=W.generateBatch(spec,10),evaluation=W.evaluate(spec,batch,{schemaValidityBps:10000,uniquenessBps:10000,referentialIntegrityBps:10000,distributionSimilarityBps:10000,privacyAttackResistanceBps:10000,utilityBps:10000,latencyMs:1,evaluatorVersion:'e1',evidenceDigest:hash('a')}).evaluation,privacy=W.privacyReview(spec,{policyVersion:'privacy-1',riskEvidenceDigest:hash('b'),reidentificationRiskBps:10,maxRiskBps:500}).review,value={job:{id:1,state:'release_review',createdBy:1,specDigest:spec.specDigest},evaluation,privacy,approval:{approvedBy:2,attestationDigest:hash('c')},providers:['kms','object_storage']};assert.equal(W.approveRelease(value).ok,true);const bad=W.approveRelease({...value,approval:{approvedBy:1,attestationDigest:hash('c')},providers:['kms']});assert.match(bad.errors.join(' '),/independent/);assert.match(bad.errors.join(' '),/object_storage/);});
test('notification messages are digest-only and signed webhooks reject replay/tampering',()=>{const message=W.notification({eventType:'release.ready',destinationRef:'ops-channel',payloadDigest:hash('d'),channel:'webhook'});assert.equal(message.containsSensitiveData,false);assert.equal(Object.hasOwn(message,'payload'),false);const secret='x'.repeat(32),body=Buffer.from('{"event":"done"}'),timestamp=1000000,signature=crypto.createHmac('sha256',secret).update(`${timestamp}.`).update(body).digest('hex');assert.equal(W.verifyWebhook(body,signature,secret,timestamp,timestamp),true);assert.equal(W.verifyWebhook(Buffer.from('tampered'),signature,secret,timestamp,timestamp),false);assert.equal(W.verifyWebhook(body,signature,secret,timestamp,timestamp+400000),false);});
test('state roles and bounded retries prevent release shortcuts',()=>{assert.equal(W.transition('draft','validated','data_steward').ok,true);assert.equal(W.transition('release_review','released','spec_author').ok,false);assert.equal(W.transition('release_review','released','release_manager').ok,true);assert.deepEqual(W.retry(1),{status:'retry',retryable:true,nextDelaySeconds:30});assert.deepEqual(W.retry(5),{status:'dead_letter',retryable:false,nextDelaySeconds:null});});
test('typed providers and usage fail closed',()=>{assert.equal(readiness({}).ready,false);assert.throws(()=>requireProviders(['kms'],{}),/not ready/);assert.match(W.usage({provider:'job_runner',operation:'generate',units:100,unitType:'records',evidenceDigest:hash('e')}).usageDigest,/^[a-f0-9]{64}$/);const env={};for(const name of W.PROVIDERS){const key=name.toUpperCase();env[`${key}_PROVIDER_ENABLED`]='true';env[`${key}_PROVIDER_URL`]=`https://${name}.example.invalid`;env[`${key}_PROVIDER_TOKEN`]='runtime';}assert.equal(readiness(env).ready,true);});
