// Custom Views - Synth Views dashboard
// 2 VIZ (volume chart, quality heatmap) + 2 NON-VIZ (spec PDF, generation rules editor)
const express = require('express');
const router = express.Router();

let _rules = [
  { id: 'rule-1', name: 'High Privacy / Low Utility', privacy: 0.95, utility: 0.45, epsilon: 0.5, notes: 'DP synthesis with tight epsilon for re-identification resistance' },
  { id: 'rule-2', name: 'Balanced Privacy/Utility', privacy: 0.7, utility: 0.78, epsilon: 2.0, notes: 'Default tradeoff for analytics-grade synthetic data' },
  { id: 'rule-3', name: 'High Utility / Low Privacy', privacy: 0.35, utility: 0.94, epsilon: 8.0, notes: 'For internal model training where reidentification risk is low' },
  { id: 'rule-4', name: 'HIPAA Strict', privacy: 0.98, utility: 0.55, epsilon: 0.3, notes: 'Medical records, k-anonymity k>=10 enforced' },
];
let _idCounter = 5;

// 1. VIZ: Generation volume time-series (rows generated per day, per dataset)
router.get('/volume', (req, res) => {
  const today = new Date();
  const datasets = ['customers_synth', 'transactions_synth', 'medical_records_synth', 'iot_telemetry_synth'];
  const series = datasets.map((name, i) => {
    const points = [];
    for (let d = 13; d >= 0; d--) {
      const dt = new Date(today.getTime() - d * 86400000);
      const base = 1200 + i * 850;
      const wave = Math.sin((d + i) * 0.6) * 400;
      const noise = ((d * 31 + i * 17) % 250) - 100;
      points.push({ date: dt.toISOString().slice(0, 10), rows: Math.max(50, Math.round(base + wave + noise)) });
    }
    return { dataset: name, points };
  });
  const totals = series.map(s => ({ dataset: s.dataset, total: s.points.reduce((a, p) => a + p.rows, 0) }));
  res.json({ ok: true, days: 14, series, totals, generated_at: new Date().toISOString() });
});

// 2. VIZ: Quality metric heatmap (metrics x datasets)
router.get('/quality-heatmap', (req, res) => {
  const metrics = ['Statistical Fidelity', 'Column Correlations', 'KS Distance', 'Privacy Score', 'Utility Score', 'Coverage'];
  const datasets = ['customers_synth', 'transactions_synth', 'medical_records_synth', 'iot_telemetry_synth', 'logs_synth'];
  const cells = [];
  metrics.forEach((m, mi) => {
    datasets.forEach((d, di) => {
      const v = Math.max(0.35, Math.min(0.99, 0.55 + ((mi * 13 + di * 7) % 45) / 100 + (mi === 3 ? 0.05 : 0)));
      cells.push({ metric: m, dataset: d, value: Number(v.toFixed(3)) });
    });
  });
  res.json({ ok: true, metrics, datasets, cells, scale: { min: 0, max: 1 } });
});

// 3. NON-VIZ: Dataset specification PDF (returns text/plain spec doc, suitable for PDF render)
router.get('/spec-pdf', (req, res) => {
  const datasetName = (req.query.dataset || 'customers_synth').toString().slice(0, 64);
  const rows = Number(req.query.rows) || 10000;
  const lines = [
    `DATASET SPECIFICATION`,
    `=====================`,
    `Dataset: ${datasetName}`,
    `Generated: ${new Date().toISOString()}`,
    `Row Count: ${rows}`,
    ``,
    `1. SCHEMA`,
    `   - id            : uuid     (primary key)`,
    `   - first_name    : string   (faker.first_name)`,
    `   - last_name     : string   (faker.last_name)`,
    `   - email         : string   (synthesized, no real PII)`,
    `   - age           : integer  (gaussian mu=38 sigma=12)`,
    `   - income        : numeric  (lognormal)`,
    `   - country       : enum     (top-25 ISO codes, weighted)`,
    `   - signup_date   : date     (2018-01-01 .. today)`,
    ``,
    `2. PRIVACY GUARANTEES`,
    `   - Differential privacy (epsilon = 2.0)`,
    `   - k-anonymity (k >= 5)`,
    `   - No real PII in any column`,
    ``,
    `3. UTILITY METRICS`,
    `   - Statistical fidelity vs real: 0.87`,
    `   - Correlation preservation:     0.92`,
    `   - Downstream ML AUC delta:      -0.014`,
    ``,
    `4. INTENDED USE`,
    `   - Model training, testing, demo. Not for production identity matching.`,
    ``,
    `5. SIGN-OFF`,
    `   - Generated by AISyntheticDataGenerator (custom-views/spec-pdf)`,
  ];
  const text = lines.join('\n');
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${datasetName}-spec.txt"`);
  res.status(200).send(text);
});

// 4. NON-VIZ: Generation rules CRUD (privacy/utility tradeoffs)
router.get('/rules', (req, res) => {
  res.json({ ok: true, rules: _rules, count: _rules.length });
});

router.post('/rules', (req, res) => {
  const b = req.body || {};
  const name = (b.name || '').toString().slice(0, 120);
  if (!name) return res.status(400).json({ ok: false, error: 'name required' });
  const rule = {
    id: `rule-${_idCounter++}`,
    name,
    privacy: Math.max(0, Math.min(1, Number(b.privacy) || 0.7)),
    utility: Math.max(0, Math.min(1, Number(b.utility) || 0.7)),
    epsilon: Number(b.epsilon) || 1.0,
    notes: (b.notes || '').toString().slice(0, 500),
  };
  _rules.push(rule);
  res.status(200).json({ ok: true, rule, count: _rules.length });
});

router.put('/rules/:id', (req, res) => {
  const idx = _rules.findIndex(r => r.id === req.params.id);
  if (idx === -1) return res.status(404).json({ ok: false, error: 'not found' });
  const b = req.body || {};
  _rules[idx] = {
    ..._rules[idx],
    ...(b.name !== undefined ? { name: String(b.name).slice(0, 120) } : {}),
    ...(b.privacy !== undefined ? { privacy: Math.max(0, Math.min(1, Number(b.privacy))) } : {}),
    ...(b.utility !== undefined ? { utility: Math.max(0, Math.min(1, Number(b.utility))) } : {}),
    ...(b.epsilon !== undefined ? { epsilon: Number(b.epsilon) } : {}),
    ...(b.notes !== undefined ? { notes: String(b.notes).slice(0, 500) } : {}),
  };
  res.json({ ok: true, rule: _rules[idx] });
});

router.delete('/rules/:id', (req, res) => {
  const before = _rules.length;
  _rules = _rules.filter(r => r.id !== req.params.id);
  res.json({ ok: true, deleted: before - _rules.length, count: _rules.length });
});

module.exports = router;
