import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { datasets } from '../services/api';
import DetailModal from '../components/DetailModal';
import ItemForm from '../components/ItemForm';
import GenerateModal from '../components/GenerateModal';
import AIResultDisplay from '../components/AIResultDisplay';

function FeaturePage({ categories }) {
  const { category } = useParams();
  const navigate = useNavigate();
  const cat = categories[category];

  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedItem, setSelectedItem] = useState(null);
  const [showDetail, setShowDetail] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [editItem, setEditItem] = useState(null);
  const [showGenerate, setShowGenerate] = useState(false);
  const [aiResult, setAiResult] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');

  const loadItems = useCallback(async () => {
    setLoading(true);
    try {
      const data = await datasets.getAll(category);
      setItems(data);
    } catch (err) {
      console.error('Failed to load items:', err);
    } finally {
      setLoading(false);
    }
  }, [category]);

  useEffect(() => {
    loadItems();
    setSelectedItem(null);
    setShowDetail(false);
    setShowForm(false);
    setShowGenerate(false);
    setAiResult(null);
  }, [category, loadItems]);

  if (!cat) {
    return <div className="error-page">Category not found. <button onClick={() => navigate('/')}>Go Home</button></div>;
  }

  const handleRowClick = async (item) => {
    try {
      const fullItem = await datasets.getOne(item.id);
      setSelectedItem(fullItem);
      setShowDetail(true);
    } catch (err) {
      console.error('Failed to load item details:', err);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this dataset?')) return;
    try {
      await datasets.delete(id);
      setItems(items.filter((i) => i.id !== id));
      setShowDetail(false);
      setSelectedItem(null);
    } catch (err) {
      console.error('Failed to delete:', err);
    }
  };

  const handleEdit = (item) => {
    setEditItem(item);
    setShowDetail(false);
    setShowForm(true);
  };

  const handleCreate = () => {
    setEditItem(null);
    setShowForm(true);
  };

  const handleFormSubmit = async (formData) => {
    try {
      if (editItem) {
        await datasets.update(editItem.id, formData);
      } else {
        await datasets.create({ ...formData, category });
      }
      setShowForm(false);
      setEditItem(null);
      loadItems();
    } catch (err) {
      console.error('Failed to save:', err);
      alert('Failed to save: ' + err.message);
    }
  };

  const handleGenerate = () => {
    setShowGenerate(true);
    setAiResult(null);
  };

  const handleGenerateResult = (result) => {
    setAiResult(result);
    setShowGenerate(false);
  };

  const handleSaveGenerated = async (result) => {
    try {
      await datasets.saveGenerated({
        category,
        name: `AI Generated - ${cat.label} - ${new Date().toLocaleDateString()}`,
        description: `Generated by AI on ${new Date().toLocaleString()}`,
        data: result.result,
        record_count: Object.values(result.result)[0]?.length || 0,
        generation_id: result.generation?.id,
      });
      setAiResult(null);
      loadItems();
    } catch (err) {
      console.error('Failed to save:', err);
      alert('Failed to save generated data');
    }
  };

  const filteredItems = items.filter((item) =>
    item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (item.description || '').toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="feature-page">
      <div className="feature-header">
        <div className="feature-header-left">
          <button className="btn btn-ghost" onClick={() => navigate('/')}>
            ← Back
          </button>
          <div className="feature-title">
            <span className="feature-icon" style={{ background: cat.color }}>{cat.icon}</span>
            <div>
              <h1>{cat.label}</h1>
              <p>{cat.description}</p>
            </div>
          </div>
        </div>
        <div className="feature-actions">
          <button className="btn btn-ai" onClick={handleGenerate}>
            🤖 Generate with AI
          </button>
          <button className="btn btn-primary" onClick={handleCreate}>
            + New Dataset
          </button>
        </div>
      </div>

      <div className="feature-toolbar">
        <div className="search-box">
          <span className="search-icon">🔍</span>
          <input
            type="text"
            placeholder="Search datasets..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
        <div className="toolbar-info">
          {filteredItems.length} dataset{filteredItems.length !== 1 ? 's' : ''}
        </div>
      </div>

      {loading ? (
        <div className="loading-state">
          <div className="spinner large" />
          <p>Loading datasets...</p>
        </div>
      ) : filteredItems.length === 0 ? (
        <div className="empty-state">
          <span className="empty-icon">{cat.icon}</span>
          <h3>No datasets yet</h3>
          <p>Create your first {cat.label.toLowerCase()} dataset or generate one with AI.</p>
          <div className="empty-actions">
            <button className="btn btn-primary" onClick={handleCreate}>+ New Dataset</button>
            <button className="btn btn-ai" onClick={handleGenerate}>🤖 Generate with AI</button>
          </div>
        </div>
      ) : (
        <div className="data-table-container">
          <table className="data-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Records</th>
                <th>Status</th>
                <th>Updated</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredItems.map((item) => (
                <tr key={item.id} onClick={() => handleRowClick(item)} className="table-row-clickable">
                  <td className="cell-name">
                    <span className="row-icon" style={{ background: cat.color }}>{cat.icon}</span>
                    {item.name}
                  </td>
                  <td className="cell-desc">{item.description}</td>
                  <td className="cell-count">{(item.record_count || 0).toLocaleString()}</td>
                  <td>
                    <span className={`status-badge status-${item.status}`}>
                      {item.status}
                    </span>
                  </td>
                  <td className="cell-date">
                    {new Date(item.updated_at).toLocaleDateString()}
                  </td>
                  <td className="cell-actions" onClick={(e) => e.stopPropagation()}>
                    <button className="btn-icon" title="View Detail" onClick={() => navigate(`/dataset/${item.id}`)}>👁️</button>
                    <button className="btn-icon" title="Edit" onClick={() => handleEdit(item)}>✏️</button>
                    <button className="btn-icon" title="Delete" onClick={() => handleDelete(item.id)}>🗑️</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {aiResult && (
        <AIResultDisplay
          result={aiResult}
          category={category}
          categoryInfo={cat}
          onSave={() => handleSaveGenerated(aiResult)}
          onClose={() => setAiResult(null)}
        />
      )}

      {showDetail && selectedItem && (
        <DetailModal
          item={selectedItem}
          category={cat}
          onClose={() => { setShowDetail(false); setSelectedItem(null); }}
          onEdit={() => handleEdit(selectedItem)}
          onDelete={() => handleDelete(selectedItem.id)}
        />
      )}

      {showForm && (
        <ItemForm
          item={editItem}
          category={category}
          categoryInfo={cat}
          onSubmit={handleFormSubmit}
          onClose={() => { setShowForm(false); setEditItem(null); }}
        />
      )}

      {showGenerate && (
        <GenerateModal
          category={category}
          categoryInfo={cat}
          onResult={handleGenerateResult}
          onClose={() => setShowGenerate(false)}
        />
      )}
    </div>
  );
}

export default FeaturePage;
